function dYdt = Equations_6(t,Y,m_i,m_c,J_c,m_t,J_t,L_t,L_p,k_ab,c_ab,k_p,c_p,k_rp,c_rp,k_s,c_s,k_b,c_b,k_ri,c_ri,k_i,c_i,a,g)
%EQUATIONS_6
%    DYDT = EQUATIONS_6(T,Y,M_I,M_C,J_C,M_T,J_T,L_T,L_P,K_AB,C_AB,K_P,C_P,K_RP,C_RP,K_S,C_S,K_B,C_B,K_RI,C_RI,K_I,C_I,A,G)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Jun-2019 10:42:10

% theta_c dtheta_c theta_t dtheta_t x_i dx_i x_c dx_c y_c dy_c x_t dx_t y_t dy_t ;

t2 = Y(2);
t3 = Y(4);
t4 = c_rp.*t2;
t5 = Y(3);
t6 = Y(1);
t7 = k_rp.*t5;
t8 = Y(6);
t9 = Y(12);
t10 = Y(11);
dYdt = [t2;(t4+t7-c_rp.*t3-k_rp.*t6)./J_c;t3;-(t4+t7-c_ri.*t3-c_rp.*t3+k_ri.*t5-k_rp.*t6)./J_t;t8;-(a.*m_i-c_i.*t8+k_i.*Y(5))./m_i;Y(8);-a;Y(10);-g;t9;-(a.*m_t-c_ab.*t9-c_b.*t9-c_s.*t9+k_ab.*t10+k_b.*t10+k_s.*t10)./m_t;Y(14);-g];
